### ISSUE TITLE
Data deleted

### ISSUE THREAD

**Issue by galaira** [ankane/pgsync#102]
First, thank you for this useful feature, but today I can't use it for security reasons.

I try to make some local tests between two databases before to use your solution.
One was pretty bad: when I try to synchronize two tables, one with 75.000 lines, the other with 16.000, and then, if I cancel quickly (to simulate some internet issue) just after the beginning of my command, all the lines are deleted in the second table, it is totally empty.

To reproduce the bug:
- Create two datatbases, db1, db2, with same schemas with postgreSQL 12.4
- Fill up one table in db1 with some lines (75000 in my case)
- Fill up same table in db2 with the same lines in db1
- Delete some lines in the table in db2 (59000 in my case)
- Change .pgsync.yml to sync from db1 to db2
- Run _pgsync schemaName.tableName_ and quickly cancel the command just after
- The table in db2 is totally empty

Done with:
- pgsync 0.6.5
- Windows  8.1
- PostgreSQL 12.4

**Comment by ankane** [comment]
Hey @galaira, pgsync truncates the destination table before syncing (unless you specify a SQL clause).

There could probably be an option to wrap the destination sync in a transaction and use delete instead of truncate (since truncate isn't MVCC safe) if you'd like to submit a PR.

**Comment by davidroman0O** [comment]
I'm not a Ruby guy at all (more go, js, rust) so I can't submit a PR but this feature could be really useful when you run a constant sync and try to query (read-only) data. 

It appear that from time to time, since tables are truncate, no data can be fetched during the sync of those tables.

I'm so sorry that I can't contribute to your project, I use it in k8s and it's really enjoyable as a CronJob!

Thx man, you're doing a great job

**Comment by ankane** [comment]
Added to the ideas list
