### ISSUE TITLE
Require one of “truncate, preserve, overwrite” flags to be selected

### ISSUE THREAD

**Issue by HarshaLaxman** [ankane/pgsync#129]
If none of the flags “truncate, preserve, overwrite” are set and there is no conditional query, a truncate cascade occurs unless defer-constraints is used
https://github.com/ankane/pgsync/blob/3c30319e14936e36a330c2407fe8926f23ae1d23/lib/pgsync/task.rb#L152-L155
https://github.com/ankane/pgsync/blob/3c30319e14936e36a330c2407fe8926f23ae1d23/lib/pgsync/task.rb#L127

I agree with using a DELETE instead https://github.com/ankane/pgsync/issues/102#issuecomment-699794542
but even with the DELETE, I think it would be helpful to require one of the flags to be set. Defaulting to Truncate/Delete is scary, especially since in some cases (conditional query or defer-constraints) this default does not occur which can lead to confusion.

**Comment by ankane** [comment]
Hey @HarshaLaxman, thanks for the suggestion, but I don't want to change the current behavior.

**Comment by SedMek** [comment]
Reviving this issue since I had an incident caused by the behaviour defaulting to truncate.
I blame myself for not RTFM, but the tool can help avoid disastrous operations. Defaulting to truncate without being explicitly instructed to is a dangerous choice.

after almost 5 years, @ankane did you have the time to reconsider and change your mind about it?
