### ISSUE TITLE
No Source Issue

### ISSUE THREAD

**Issue by priyankasingh23** [ankane/pgsync#157]
Hi,

I am trying to synchronize the database over two system 
I want to run  pgsync command at every 15 min to sync the database, So I added in crontab as *15 * * * * /usr/local/bin/python /folder/main.py    
but Everytime I am getting the error as "No Source"
/usr/bin/crontab  // location of crontab
/usr/local/bin/pgsync //location of pgsync binary

But when I am trying to run the same manually with "/usr/local/bin/python  /folder/main.py "from any of the above directory like /usr/bin or /usr/local/bin after adding the .pgsync.yml file there, it worked
main.py is the python code where I am calling giving command "pgsync --defer-constraints --preserve"
But whenever it is running as cron job it is giving error as NO source.
I am doing this docker container

`What should I do??

**Comment by ankane** [comment]
Hey @priyankasingh23, it sounds like pgsync isn't finding `.pgsync.yml`. You can either change the working directory or use the `--config` option to specify the absolute path. This is more of a general cron question, so please use Stack Overflow for additional help.

**Comment by exotexot** [comment]
I also can't get pgsync to run in a crontab either locally (macOS via homebrew) or on an Ubuntu server (tried docker and gem)...

**Comment by exotexot** [comment]
I was able to get it working using a cronjob and docker by removing the -it flag when running the docker, and I also added -rm to remove the container so it stops re-creating containers over and over again.

docker run --rm ankane/pgsync

On my ubuntu server I also had to add
sudo chmod 666 /var/run/docker.sock

in order to run the docker without the need of sudo
