### ISSUE TITLE
How is this better than the native replication options?

### ISSUE THREAD

**Issue by osklyarenko** [ankane/pgsync#79]
Didn’t find mentions of it in the readme

**Comment by osklyarenko** [comment]
I see a line saying that speed is better than traditional tools. I assume this includes replication 

Would be great to be a bit more specific there. Like adding a paragraph taking about why this tool was developed and what problem were you trying to solve.

**Comment by chris-np** [comment]
I can tell you what I _hope_ the answer is. I ended up here looking for something that I can use to sync production data to a development database where replication isn't an option. It might be on a laptop for example and dump/restore isn't ideal because of the size of the data. I want to only sync certain tables (ideally just by INSERTing rows that don't already exist) and ignore any sort of administrative differences like users and GRANTs. Also, I want to avoid doing this if the development (target) database is a newer version (migrations run) which I can easily check in a script.

**Comment by ankane** [comment]
Hey @osklyarenko, thanks for the suggestion. I updated the readme to make it clear it's more like `pg_dump`/`pg_restore` than replication. The reasons for developing it are listed in the intro.
